name: Fetch Shopify Orders

on:
  schedule:
    - cron:  '0 0 * * *'       # daily at 00:00 UTC
  workflow_dispatch:         # manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch orders
        env:
          SHOP_DOMAIN: ${{ secrets.SHOP_DOMAIN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          API_VERSION: '2024-04'
        run: |
          python fetch_orders.py

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update Shopify orders data"
          file_pattern: docs/data/orders.json


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
